name: Testing Self-hosted Runner
on:
    workflow_dispatch:

jobs:
    testing:
        runs-on: [self-hosted, Linux, dev, lab]
        steps:
            - name: Echo Content
              run: |
                echo Ok
                sleep 15s