name: Exploring Variables and Secrets

on:
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t champ886/imageName:latest

            - name: Docker Login
              run: docker login --username=champ886 --password=DeskServ08#

            - name: Docker Publish
              run: docker push docker.io/champ886/imageName:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: docker run -d -p 8080:80 docker.io/champ886/imageName:latest